name: panel_resume
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.2.1+2
  dio:
  get_storage: ^2.0.2
  logger: ^1.0.0-nullsafety.0
  flutter_svg: ^1.0.3
  json_annotation: ^4.4.0
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^7.6.1
  freezed_annotation:
  retrofit:


dev_dependencies:
  flutter_lints: ^1.0.0
  freezed: ^1.1.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  retrofit_generator:

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: poppin
      fonts:
        - asset: assets/fonts/poppin.ttf